# Generated by Django 5.1.4 on 2025-04-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProteinBasicInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "IDName",
                    models.CharField(max_length=255, unique=True, verbose_name="蛋白质ID"),
                ),
                (
                    "SequenceFeature",
                    models.TextField(blank=True, null=True, verbose_name="序列特征"),
                ),
            ],
            options={
                "verbose_name": "蛋白质基本信息",
                "verbose_name_plural": "蛋白质基本信息",
                "db_table": "protein_basic_info",
            },
        ),
        migrations.CreateModel(
            name="ProteinComprehensiveFunctionInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "IDName",
                    models.CharField(max_length=255, unique=True, verbose_name="蛋白质ID"),
                ),
                (
                    "Function",
                    models.TextField(blank=True, null=True, verbose_name="功能信息"),
                ),
            ],
            options={
                "verbose_name": "蛋白质综合功能信息",
                "verbose_name_plural": "蛋白质综合功能信息",
                "db_table": "protein_comprehensive_function_info",
            },
        ),
        migrations.CreateModel(
            name="ProteinComprehensiveInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "IDName",
                    models.CharField(max_length=255, unique=True, verbose_name="蛋白质ID"),
                ),
                (
                    "CompleteInfo",
                    models.TextField(blank=True, null=True, verbose_name="完整信息"),
                ),
            ],
            options={
                "verbose_name": "蛋白质综合信息",
                "verbose_name_plural": "蛋白质综合信息",
                "db_table": "protein_comprehensive_info",
            },
        ),
        migrations.CreateModel(
            name="ProteinStructureInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "IDName",
                    models.CharField(max_length=255, unique=True, verbose_name="蛋白质ID"),
                ),
                (
                    "Embedding",
                    models.TextField(blank=True, null=True, verbose_name="嵌入向量"),
                ),
                ("Domain", models.TextField(blank=True, null=True, verbose_name="结构域")),
            ],
            options={
                "verbose_name": "蛋白质结构信息",
                "verbose_name_plural": "蛋白质结构信息",
                "db_table": "protein_structure_info",
            },
        ),
        migrations.CreateModel(
            name="ProteinFunctionAnnotation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("IDName", models.CharField(max_length=255, verbose_name="蛋白质ID")),
                (
                    "FunctionType",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="功能类型"
                    ),
                ),
                (
                    "Description",
                    models.TextField(blank=True, null=True, verbose_name="功能描述"),
                ),
            ],
            options={
                "verbose_name": "蛋白质功能注释",
                "verbose_name_plural": "蛋白质功能注释",
                "db_table": "protein_function_annotation",
                "unique_together": {("IDName", "FunctionType")},
            },
        ),
        migrations.CreateModel(
            name="ProteinFunctionDomainRelation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("IDName", models.CharField(max_length=255, verbose_name="蛋白质ID")),
                (
                    "Function",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="功能"
                    ),
                ),
                (
                    "Domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="结构域"
                    ),
                ),
                (
                    "Relation",
                    models.TextField(blank=True, null=True, verbose_name="关系描述"),
                ),
            ],
            options={
                "verbose_name": "蛋白质功能-结构域关系",
                "verbose_name_plural": "蛋白质功能-结构域关系",
                "db_table": "protein_function_domain_relation",
                "unique_together": {("IDName", "Function", "Domain")},
            },
        ),
        migrations.CreateModel(
            name="ProteinLocationSequenceRelation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("IDName", models.CharField(max_length=255, verbose_name="蛋白质ID")),
                (
                    "Location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="亚细胞定位"
                    ),
                ),
                (
                    "Sequence",
                    models.TextField(blank=True, null=True, verbose_name="序列特征"),
                ),
                (
                    "Relation",
                    models.TextField(blank=True, null=True, verbose_name="关系描述"),
                ),
            ],
            options={
                "verbose_name": "蛋白质定位-序列关系",
                "verbose_name_plural": "蛋白质定位-序列关系",
                "db_table": "protein_location_sequence_relation",
                "unique_together": {("IDName", "Location")},
            },
        ),
        migrations.CreateModel(
            name="ProteinStructureFunctionRelation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("IDName", models.CharField(max_length=255, verbose_name="蛋白质ID")),
                (
                    "Structure",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="结构"
                    ),
                ),
                (
                    "Function",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="功能"
                    ),
                ),
                (
                    "Relation",
                    models.TextField(blank=True, null=True, verbose_name="关系描述"),
                ),
            ],
            options={
                "verbose_name": "蛋白质结构-功能关系",
                "verbose_name_plural": "蛋白质结构-功能关系",
                "db_table": "protein_structure_function_relation",
                "unique_together": {("IDName", "Structure", "Function")},
            },
        ),
        migrations.CreateModel(
            name="ProteinSubcellularLocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("IDName", models.CharField(max_length=255, verbose_name="蛋白质ID")),
                (
                    "Location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="亚细胞定位"
                    ),
                ),
                (
                    "Confidence",
                    models.FloatField(blank=True, null=True, verbose_name="置信度"),
                ),
            ],
            options={
                "verbose_name": "蛋白质亚细胞定位",
                "verbose_name_plural": "蛋白质亚细胞定位",
                "db_table": "protein_subcellular_location",
                "unique_together": {("IDName", "Location")},
            },
        ),
    ]
