# Generated by Django 5.1.3 on 2025-05-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protein_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proteinlocationsequencerelation",
            old_name="Sequence",
            new_name="SequenceFeature",
        ),
        migrations.AlterUniqueTogether(
            name="proteinfunctionannotation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="proteinfunctiondomainrelation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="proteinlocationsequencerelation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="proteinstructurefunctionrelation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="proteinsubcellularlocation",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="proteincomprehensiveinfo",
            name="CompleteInfo",
        ),
        migrations.AddField(
            model_name="proteincomprehensivefunctioninfo",
            name="EC",
            field=models.TextField(blank=True, null=True, verbose_name="EC号"),
        ),
        migrations.AddField(
            model_name="proteincomprehensivefunctioninfo",
            name="GO",
            field=models.TextField(blank=True, null=True, verbose_name="GO注释"),
        ),
        migrations.AddField(
            model_name="proteincomprehensivefunctioninfo",
            name="SubcellularLocation",
            field=models.TextField(blank=True, null=True, verbose_name="亚细胞定位"),
        ),
        migrations.AddField(
            model_name="proteincomprehensiveinfo",
            name="Function",
            field=models.TextField(blank=True, null=True, verbose_name="功能"),
        ),
        migrations.AddField(
            model_name="proteincomprehensiveinfo",
            name="SequenceFeature",
            field=models.TextField(blank=True, null=True, verbose_name="序列特征"),
        ),
        migrations.AddField(
            model_name="proteincomprehensiveinfo",
            name="SubcellularLocation",
            field=models.TextField(blank=True, null=True, verbose_name="亚细胞定位"),
        ),
        migrations.AddField(
            model_name="proteinfunctionannotation",
            name="EC",
            field=models.TextField(blank=True, null=True, verbose_name="EC号"),
        ),
        migrations.AddField(
            model_name="proteinfunctionannotation",
            name="Function",
            field=models.TextField(blank=True, null=True, verbose_name="功能"),
        ),
        migrations.AddField(
            model_name="proteinfunctionannotation",
            name="GO",
            field=models.TextField(blank=True, null=True, verbose_name="GO注释"),
        ),
        migrations.AddField(
            model_name="proteinlocationsequencerelation",
            name="SubcellularLocation",
            field=models.TextField(blank=True, null=True, verbose_name="亚细胞定位"),
        ),
        migrations.AddField(
            model_name="proteinstructurefunctionrelation",
            name="Domain",
            field=models.TextField(blank=True, null=True, verbose_name="结构域"),
        ),
        migrations.AddField(
            model_name="proteinstructurefunctionrelation",
            name="Embedding",
            field=models.TextField(blank=True, null=True, verbose_name="嵌入向量"),
        ),
        migrations.AddField(
            model_name="proteinsubcellularlocation",
            name="SubcellularLocation",
            field=models.TextField(blank=True, null=True, verbose_name="亚细胞定位"),
        ),
        migrations.AlterField(
            model_name="proteinbasicinfo",
            name="IDName",
            field=models.TextField(blank=True, null=True, verbose_name="蛋白质ID"),
        ),
        migrations.AlterField(
            model_name="proteincomprehensivefunctioninfo",
            name="IDName",
            field=models.TextField(blank=True, null=True, verbose_name="蛋白质ID"),
        ),
        migrations.AlterField(
            model_name="proteincomprehensiveinfo",
            name="IDName",
            field=models.TextField(blank=True, null=True, verbose_name="蛋白质ID"),
        ),
        migrations.AlterField(
            model_name="proteinfunctionannotation",
            name="IDName",
            field=models.TextField(blank=True, null=True, verbose_name="蛋白质ID"),
        ),
        migrations.AlterField(
            model_name="proteinfunctiondomainrelation",
            name="Domain",
            field=models.TextField(blank=True, null=True, verbose_name="结构域"),
        ),
        migrations.AlterField(
            model_name="proteinfunctiondomainrelation",
            name="Function",
            field=models.TextField(blank=True, null=True, verbose_name="功能"),
        ),
        migrations.AlterField(
            model_name="proteinfunctiondomainrelation",
            name="IDName",
            field=models.TextField(blank=True, null=True, verbose_name="蛋白质ID"),
        ),
        migrations.AlterField(
            model_name="proteinlocationsequencerelation",
            name="IDName",
            field=models.TextField(blank=True, null=True, verbose_name="蛋白质ID"),
        ),
        migrations.AlterField(
            model_name="proteinstructurefunctionrelation",
            name="Function",
            field=models.TextField(blank=True, null=True, verbose_name="功能"),
        ),
        migrations.AlterField(
            model_name="proteinstructurefunctionrelation",
            name="IDName",
            field=models.TextField(blank=True, null=True, verbose_name="蛋白质ID"),
        ),
        migrations.AlterField(
            model_name="proteinstructureinfo",
            name="IDName",
            field=models.TextField(blank=True, null=True, verbose_name="蛋白质ID"),
        ),
        migrations.AlterField(
            model_name="proteinsubcellularlocation",
            name="IDName",
            field=models.TextField(blank=True, null=True, verbose_name="蛋白质ID"),
        ),
        migrations.RemoveField(
            model_name="proteinfunctionannotation",
            name="Description",
        ),
        migrations.RemoveField(
            model_name="proteinfunctionannotation",
            name="FunctionType",
        ),
        migrations.RemoveField(
            model_name="proteinfunctiondomainrelation",
            name="Relation",
        ),
        migrations.RemoveField(
            model_name="proteinlocationsequencerelation",
            name="Location",
        ),
        migrations.RemoveField(
            model_name="proteinlocationsequencerelation",
            name="Relation",
        ),
        migrations.RemoveField(
            model_name="proteinstructurefunctionrelation",
            name="Relation",
        ),
        migrations.RemoveField(
            model_name="proteinstructurefunctionrelation",
            name="Structure",
        ),
        migrations.RemoveField(
            model_name="proteinsubcellularlocation",
            name="Confidence",
        ),
        migrations.RemoveField(
            model_name="proteinsubcellularlocation",
            name="Location",
        ),
    ]
