# Generated by Django 5.1.4 on 2025-04-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitlog",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("page_view", "页面访问"),
                    ("protein_embedding", "蛋白质嵌入"),
                    ("matrix_view", "矩阵查看"),
                    ("data_analysis", "数据分析"),
                    ("similar_search", "相似酶搜索"),
                    ("upload_file", "文件上传"),
                    ("other", "其他操作"),
                ],
                default="page_view",
                max_length=50,
                verbose_name="操作类型",
            ),
        ),
        migrations.AddField(
            model_name="visitlog",
            name="page_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="访问页面URL"
            ),
        ),
        migrations.AddField(
            model_name="visitlog",
            name="request_data",
            field=models.TextField(blank=True, null=True, verbose_name="请求数据"),
        ),
        migrations.AddIndex(
            model_name="visitlog",
            index=models.Index(
                fields=["visit_time"], name="index_visit_visit_t_e7bcf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitlog",
            index=models.Index(
                fields=["operation_type"], name="index_visit_operati_bdf4dc_idx"
            ),
        ),
    ]
